apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-svc
  name: dep-svc
  namespace: basant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-svc
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dep-svc
  name: dep-svc-latest
  namespace: basant
spec:
  clusterIP: 10.102.50.246
  clusterIPs:
  - 10.102.50.246
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dep-svc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
